;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;sentence jump table
;this is NOT machine generated
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
sentence_table 
	.byte look_verb_id
	.word look_sub
	.byte look_in_verb_id
	.word look_in_sub
	.byte inventory_verb_id
	.word inventory_sub
	.byte n_verb_id
	.word move_player
	.byte ne_verb_id
	.word move_player
	.byte nw_verb_id
	.word move_player	
	.byte s_verb_id
	.word move_player
	.byte e_verb_id
	.word move_player
	.byte w_verb_id
	.word move_player
	.byte se_verb_id
	.word move_player	
	.byte sw_verb_id
	.word move_player	
	.byte up_verb_id
	.word move_player	
	.byte down_verb_id
	.word move_player	
	.byte get_verb_id
	.word get_sub
	.byte out_verb_id
	.word move_player	
	.byte enter_verb_id
	.word enter_sub
	.byte drop_verb_id
	.word drop_sub
	.byte examine_verb_id
	.word look_at_sub
	.byte put_verb_id
	.word put_sub
	.byte open_verb_id
	.word open_sub
	.byte close_verb_id
	.word close_sub	
	.byte smell_verb_id
	.word smell_sub
	.byte listen_verb_id
	.word listen_sub
	.byte quit_verb_id
	.word quit_sub
	.byte lock_verb_id
	.word lock_sub
	.byte unlock_verb_id
	.word unlock_sub
	.byte wear_verb_id
	.word wear_sub
	.byte 255
	.byte save_verb_id
	.word save_sub
	.byte restore_verb_id
	.word restore_sub	
