n_verb_id equ 0
s_verb_id equ 1
e_verb_id equ 2
w_verb_id equ 3
ne_verb_id equ 4
se_verb_id equ 5
sw_verb_id equ 6
nw_verb_id equ 7
up_verb_id equ 8
down_verb_id equ 9
enter_verb_id equ 10
out_verb_id equ 11
go_verb_id equ 12
get_verb_id equ 13
give_verb_id equ 14
inventory_verb_id equ 15
kill_verb_id equ 16
drop_verb_id equ 17
light_verb_id equ 18
look_verb_id equ 19
examine_verb_id equ 20
look_in_verb_id equ 21
search_verb_id equ 22
open_verb_id equ 23
lock_verb_id equ 24
unlock_verb_id equ 25
close_verb_id equ 26
eat_verb_id equ 27
drink_verb_id equ 28
put_verb_id equ 29
quit_verb_id equ 30
smell_verb_id equ 31
listen_verb_id equ 32
wait_verb_id equ 33
climb_verb_id equ 34
yell_verb_id equ 35
jump_verb_id equ 36
talk_to_verb_id equ 37
turn_on_verb_id equ 38
turn_off_verb_id equ 39
wear_verb_id equ 40
save_verb_id equ 41
restore_verb_id equ 42
push_verb_id equ 43
read_verb_id equ 44
use_verb_id equ 45
again_verb_id equ 46
shoot_verb_id equ 47
break_verb_id equ 48
talk_verb_id equ 49
go_to_verb_id equ 50
what_verb_id equ 51
ware_verb_id equ 52
sneak_verb_id equ 53
echo_verb_id equ 54
